### ISSUE TITLE
bear: ERROR: wrapper: Internal error

### ISSUE THREAD

**Issue by egberts** [rizsotto/Bear#168]
Trying out Bear for the first time....

And its to the Mozilla JavaScript engine (very, very big).

```
$ bear -vvvv build
bear: DEBUG: parse_args_for_intercept_build: Raw arguments ['/usr/local/bin/bear', '-vvvv', 'build']
bear: DEBUG: parse_args_for_intercept_build: Parsed arguments: Namespace(append=False, build=['build'], cc='cc', cdb='compile_commands.json', cxx='c++', libear='/usr/local/lib64/libear.so', verbose=4)
bear: DEBUG: run_build: run build ['build'], in environment: {'SSH_ASKPASS': '/usr/libexec/openssh/gnome-ssh-askpass', 'HOSTNAME': 'somewhere.localdomain', 'GLADE_PIXMAP_PATH': ':', 'ALL_PROXY': 'socks://proxy01.example.com:3128/', 'GIT_PS1_SHOWDIRTYSTATE': '1', 'NO_PROXY': '127.0.0.0/8,::1,192.168.0.0/16,172.28.128.0/16,10.0.0.0/8', 'http_proxy': 'http://proxy01.example.com:3128/', 'FTP_PROXY': 'http://proxy01.example.com:3128/', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'XDG_MENU_PREFIX': 'xfce-', 'INTERCEPT_BUILD_TARGET_DIR': '/tmp/intercept-MMOy4U', 'LOGNAME': 'enduser', 'USER': 'enduser', 'HOME': '/home/enduser', 'PATH': '/home/enduser/.local/bin:/home/enduser/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin:/usr/bin:/usr/X11R6/bin:/common/utils/bin', 'DISPLAY': ':1001', 'SSH_AGENT_PID': '30253', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'XAUTHORITY': '/home/enduser/.Xauthority', 'GIT_PS1_SHOWSTASHSTATE': '1', 'SHLVL': '3', 'NX_SESSION_ID': 'D108FAD764566F652EE770F1F050F4D7', 'GLADE_MODULE_PATH': ':', 'NXDIR': '/usr/NX', 'NX_CLIENT': '/usr/NX/bin/nxclient', 'HISTSIZE': '1000', 'GIT_PS1_SHOWUPSTREAM': 'auto', 'https_proxy': 'http://proxy01.example.com:3128/', 'XDG_RUNTIME_DIR': '/run/user/10013', 'WINDOWID': '63003530', 'NX_CUPS_BIN': '/usr/bin', 'GLADE_CATALOG_PATH': ':', 'GPG_AGENT_INFO': '/home/enduser/.gnupg/S.gpg-agent:30264:1', 'NX_SYSTEM': '/usr/NX', 'USERNAME': 'enduser', 'LD_PRELOAD': '/usr/local/lib64/libear.so', 'all_proxy': 'socks://proxy01.example.com:3128/', 'NX_TEMP': '/tmp', 'COBBLER_SERVER': 'cobbler-server.example.com', 'SSH_AUTH_SOCK': '/tmp/ssh-ZOxGMFBAScwA/agent.30252', 'VTE_VERSION': '3804', 'ftp_proxy': 'http://proxy01.example.com:3128/', 'PULSE_CONFIG': '/usr/NX/var/run/nxdevice/D-1001-DD08FAD76E566F659EE770F6F050F0D7/audio/daemon.conf', 'KRB5CCNAME': 'FILE:/tmp/krb5cc_10013_XXXXxKZ4JA', 'PULSE_SERVER': '/usr/NX/var/run/nxdevice/D-1001-DD08FAD76E566F659EE770F6F050F0D7/audio/native.socket', 'PULSE_SCRIPT': '/usr/NX/var/run/nxdevice/D-1001-DD08FAD76E566F659EE770F6F050F0D7/audio/default.pa', 'QT_GRAPHICSSYSTEM_CHECKED': '1', 'XDG_CURRENT_DESKTOP': 'XFCE', 'XDG_SESSION_ID': '3392', 'SESSION_MANAGER': 'local/unix:@/tmp/.ICE-unix/30229,unix/unix:/tmp/.ICE-unix/30229', '_': '/usr/local/bin/bear', 'HTTPS_PROXY': 'http://proxy01.example.com:3128/', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-Y6Ajx6ZgHY,guid=81fe566443c39a4958bd91f9593ed831', 'DESKTOP_SESSION': 'xfce', 'GIT_PS1_SHOWUNTRACKEDFILES': '1', 'XDG_CONFIG_DIRS': '/etc/xdg', 'OLDPWD': '/home/enduser/work', 'HTTP_PROXY': 'http://proxy01.example.com:3128/', 'LS_COLORS': 'rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:', 'HISTCONTROL': 'ignoredups', 'no_proxy': 'localhost,127.0.0.0/8,::1,192.168.0.0/16,172.28.128.0/16,10.0.0.0/8', 'PWD': '/srv/git/some-repo/mozjs', 'MAIL': '/var/spool/mail/enduser', 'PULSE_CLIENTCONFIG': '/usr/NX/var/run/nxdevice/D-1001-DD08FAD76E566F659EE770F6F050F0D7/audio/client.conf', 'XDG_DATA_DIRS': '/usr/local/share:/usr/share'}
bear: ERROR: wrapper: Internal error.
Traceback (most recent call last):
  File "/usr/local/bin/bear", line 134, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/bin/bear", line 182, in intercept_build
    exit_code, current = capture(args)
  File "/usr/local/bin/bear", line 205, in capture
    exit_code = run_build(args.build, env=environment)
  File "/usr/local/bin/bear", line 593, in run_build
    exit_code = subprocess.call(command, *args, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
bear: ERROR: wrapper: Please report this bug and attach the output to the bug report
$  

```

**Comment by rizsotto** [comment]
Thanks for the report! Correct me if I'm wrong, but without `bear` you would call `./build`. If this is the case please re-run the command as `bear -vvvv ./build`.

**Comment by rizsotto** [comment]
Please reopen if it's still an issue.
