### ISSUE TITLE
Exception on scripts with command arguments containing iso-8859 characters

### ISSUE THREAD

**Issue by dengste** [rizsotto/Bear#185]
This is on Debian Linux, using bear v2.3.9, Python 2.7.13 and locale 'en_US.UTF-8'.

We have a shell script in our build process that runs 'sed' with some special characters as arguments. The script is encoded in iso-8859-1 format, and running it with 'bear' results in a backtrace. You can reproduce this by creating a script 'foobar.sh' simply containing

     #!/bin/bash
     touch foo
     sed -e "s/©//" foo

Make sure to save that script with an iso-latin-1 encoding, so that 'file foobar.sh' returns 'ISO-8859 text executable'. When I now run

    bear -vvvv ./foobar.sh

I get the following backtrace:

```
bear: DEBUG: parse_args_for_intercept_build: Raw arguments ['/usr/local/bin/bear', '-vvvv', './foobar.sh']
bear: DEBUG: parse_args_for_intercept_build: Parsed arguments: Namespace(append=False, build=['./foobar.sh'], cc='cc', cdb='compile_commands.json', cxx='c++', libear='/usr/local/lib/libear.so', verbose=4)
bear: DEBUG: run_build: run build ['./foobar.sh'], in environment: {stripped for privacy reasons}
libear: (/home/engsterd/Bear/libear/ear.c:529) mbstowcs: Invalid or incomplete multibyte or wide character
libear: (/home/engsterd/Bear/libear/ear.c:494) writing json problem: Invalid or incomplete multibyte or wide character
bear: DEBUG: run_build: build finished with exit code: 1
bear: DEBUG: parse_exec_trace: parse exec trace file: /tmp/intercept-VgjCGM/execution.SoSxg9
bear: ERROR: wrapper: Internal error.
Traceback (most recent call last):
  File "/usr/local/bin/bear", line 144, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/bin/bear", line 192, in intercept_build
    exit_code, current = capture(args)
  File "/usr/local/bin/bear", line 220, in capture
    return exit_code, iter(set(current))
  File "/usr/local/bin/bear", line 233, in compilations
    for call in exec_calls:
  File "/usr/local/bin/bear", line 217, in <genexpr>
    calls = (parse_exec_trace(file) for file in exec_trace_files(tmp_dir))
  File "/usr/local/bin/bear", line 275, in parse_exec_trace
    entry = json.load(handler)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 36 (char 35)
bear: ERROR: wrapper: Please report this bug and attach the output to the bug report
```

Converting the script to UTF-8 solves this issue, but still it'd be nice if bear could handle this.

**Comment by rizsotto** [comment]
Thanks for this report! I will look at it on the weekend. (I'm happy with that you've provided the test. Thanks for it.)

**Comment by rizsotto** [comment]
There might be a fix for this on latest master (version 2.4.0).

**Comment by rizsotto** [comment]
The issue is still valid, have functional test for it, but don't know how to fix it.

**Comment by komar007** [comment]
It seems 2.3.11 fails on the test while 2.4.2 does not. Has it been fixed (indirectly)?

**Comment by rizsotto** [comment]
I have version 3.0.18, but that still fails... I really don't get how the OS or the shell deals with encoded script files.

If it's working with 2.4.2, that's just a miracle. :smile:

**Comment by komar007** [comment]
So far I have only been able to reproduce this problem using 2.3.11 from ubuntu:bionic-20190204 docker image.
I have compiled 2.3.11 and 2.4.2 locally and both work fine.
