### ISSUE TITLE
Bear fails when watching godot-engine build

### ISSUE THREAD

**Issue by BonaBeavis** [rizsotto/Bear#209]
What do you need for reproducing?

```
bear: ERROR: wrapper: Internal error.
Traceback (most recent call last):
  File "/usr/bin/bear", line 134, in wrapper
    return function(*args, **kwargs)
  File "/usr/bin/bear", line 182, in intercept_build
    exit_code, current = capture(args)
  File "/usr/bin/bear", line 210, in capture
    return exit_code, iter(set(current))
  File "/usr/bin/bear", line 223, in compilations
    for call in exec_calls:
  File "/usr/bin/bear", line 207, in <genexpr>
    calls = (parse_exec_trace(file) for file in exec_trace_files(tmp_dir))
  File "/usr/bin/bear", line 265, in parse_exec_trace
    entry = json.load(handler)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 36 (char 35)
bear: ERROR: wrapper: Please report this bug and attach the output to the bug report
Makefile:12: recipe for target 'build-godot-engine' failed
```

[report.txt](https://github.com/rizsotto/Bear/files/1869216/report.txt)

**Comment by rizsotto** [comment]
Thanks for this report. I'm moving house this week, will come back to it next week.

**Comment by BonaBeavis** [comment]
Hi,

thanks for the support, the verbose output is attached to my first post, the report.txt link at the end.

```
❯ metameat bear --version
bear 2.3.6

❯ metameat lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

**Comment by rizsotto** [comment]
Thanks to come back. It looks this bug was fixed the latest release. (On master branch the same function catch the exception about failed JSON file read.) Could you try the latest version?

**Comment by BonaBeavis** [comment]
Thanks, works with the 3.0.0 branch.

**Comment by rizsotto** [comment]
This branch is not yet released. :smile: I recommend the 2.3.11 release from master branch.

**Comment by BonaBeavis** [comment]
It works but the compile commands are empty... Do you want to debug this, or should I wait for the release?

**Comment by rizsotto** [comment]
Was the empty output from the `master` branch? If yes, it's a relevant thing and would be happy to fix it. (If it was from the `3.x` branch, please do not spend time on it.)
